import { relations, sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

/**
 * Money is stored as integer micro-units (1e-6 USD) everywhere.
 *
 * Float dollars accumulate rounding error, and the first place it shows up is
 * a credit ledger whose rows do not sum to the recorded balance. Micro-units
 * make arithmetic exact and reconciliation a no-op instead of a judgement call.
 */
export const MICRO = 1_000_000;

/**
 * 1 credit = USD 0.01 = 10,000 micro-credits.
 *
 * Stated once, in one place, because the ratio appears in three files and a
 * mismatch between them is a silent 100x error in someone's balance.
 */
export const MICRO_PER_CREDIT = 10_000;

export const generationType = pgEnum("generation_type", ["video", "image"]);

/**
 * `image` rows are start frames generated by the image model. They exist as
 * first-class rows so a generated start frame is reusable and auditable rather
 * than an orphaned blob in storage.
 */
export const generationStatus = pgEnum("generation_status", [
  "queued", // row written, credits reserved, nothing submitted yet
  "submitting", // worker is POSTing to OpenRouter
  "generating", // accepted upstream, polling
  "downloading", // upstream done, fetching bytes into our storage
  "completed",
  "failed", // upstream reported failure
  "cancelled", // user cancelled locally
  "expired", // exceeded JOB_MAX_AGE_MINUTES
]);

export const terminalStatuses = ["completed", "failed", "cancelled", "expired"] as const;
export type TerminalStatus = (typeof terminalStatuses)[number];
export const isTerminal = (s: string): s is TerminalStatus =>
  (terminalStatuses as readonly string[]).includes(s);

export const ledgerReason = pgEnum("ledger_reason", [
  "signup_grant",
  "job_reserve",
  "job_refund",
  "job_reconcile",
  "admin_adjust",
  "admin_topup",
]);

export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey(), // == Supabase auth user id
    email: text("email").notNull(),
    passwordHash: text("password_hash"),
    name: text("name"),
    avatarUrl: text("avatar_url"),

    /** Balance in micro-credits. Never negative -- enforced by the CHECK below. */
    credits: bigint("credits", { mode: "number" }).notNull().default(0),

    isAdmin: boolean("is_admin").notNull().default(false),
    /** Set when this user is rate limited by the global daily cap, for the UI. */
    spendBlockedUntil: timestamp("spend_blocked_until", { withTimezone: true }),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("users_email_key").on(sql`lower(${t.email})`),
    // The backstop. Application code uses a conditional UPDATE, but a CHECK
    // constraint means a bug anywhere still cannot mint negative credits.
    check("users_credits_non_negative", sql`${t.credits} >= 0`),
    index("users_created_at_idx").on(t.createdAt),
  ],
);

export const authSessions = pgTable(
  "auth_sessions",
  {
    tokenHash: text("token_hash").primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("auth_sessions_user_id_idx").on(t.userId)],
);

export const generations = pgTable(
  "generations",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    type: generationType("type").notNull(),

    // ---- request ---------------------------------------------------------
    model: text("model").notNull(),
    prompt: text("prompt").notNull(),
    enhancedPrompt: text("enhanced_prompt"),
    preset: text("preset"),
    params: jsonb("params").$type<Record<string, unknown>>().notNull().default({}),

    // ---- upstream --------------------------------------------------------
    status: generationStatus("status").notNull().default("queued"),
    openrouterJobId: text("openrouter_job_id"),
    pollingUrl: text("polling_url"),
    error: text("error"),

    // ---- our copies ------------------------------------------------------
    outputUrl: text("output_url"), // storage key, not a public URL
    sourceImageUrl: text("source_image_url"), // start frame, storage key
    mimeType: text("mime_type"),
    bytes: integer("bytes"),

    /**
     * Every output, for jobs that produce more than one.
     *
     * `output_url` holds the first item and remains the single-output path, so
     * the gallery, the detail page and the media route all work unchanged for
     * video. This column is what makes an `n: 4` image job representable without
     * inventing four rows — which would have meant four credits holds, four
     * statuses and four gallery entries for one user action.
     */
    outputs: jsonb("outputs")
      .$type<Array<{ key: string; mimeType: string; bytes: number }>>()
      .notNull()
      .default([]),

    // ---- money -----------------------------------------------------------
    /** micro-USD. What we told the user before submitting. */
    costEstimateMicro: bigint("cost_estimate_micro", { mode: "number" }).notNull().default(0),
    /** micro-USD. What OpenRouter actually billed, from usage.cost. */
    costActualMicro: bigint("cost_actual_micro", { mode: "number" }),
    /** micro-credits currently held for this job. Refunded when it settles. */
    creditsHeld: bigint("credits_held", { mode: "number" }).notNull().default(0),

    // ---- visibility ------------------------------------------------------
    isPublic: boolean("is_public").notNull().default(false),

    // ---- worker scheduling ----------------------------------------------
    /** The worker only claims rows where this is in the past. */
    nextPollAt: timestamp("next_poll_at", { withTimezone: true }).notNull().defaultNow(),
    attempts: integer("attempts").notNull().default(0),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (t) => [
    index("generations_user_created_idx").on(t.userId, t.createdAt),
    // The worker's hot query: due rows, oldest first.
    index("generations_due_idx").on(t.nextPollAt).where(sql`${t.status} in ('queued','submitting','generating','downloading')`),
    index("generations_status_idx").on(t.status),
    index("generations_public_created_idx").on(t.createdAt).where(sql`${t.isPublic} = true`),
    uniqueIndex("generations_job_key").on(t.openrouterJobId),
    check("generations_estimate_non_negative", sql`${t.costEstimateMicro} >= 0`),
  ],
);

/**
 * Append-only, enforced by the database.
 *
 * A ledger that can be UPDATEd is not an audit trail, and an audit trail is the
 * only reason to keep a ledger. The trigger below makes immutability a property
 * of the schema rather than a convention every future contributor must
 * remember.
 */
export const creditLedger = pgTable(
  "credit_ledger",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    generationId: uuid("generation_id").references(() => generations.id, {
      onDelete: "set null",
    }),
    /** Negative = spent, positive = granted or refunded. Never zero. */
    delta: bigint("delta", { mode: "number" }).notNull(),
    reason: ledgerReason("reason").notNull(),
    /** Snapshot after this row applied, so the ledger is self-auditing. */
    balanceAfter: bigint("balance_after", { mode: "number" }).notNull(),
    metadata: jsonb("metadata").$type<Record<string, unknown>>(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("credit_ledger_user_created_idx").on(t.userId, t.createdAt),
    index("credit_ledger_generation_idx").on(t.generationId),
    check("credit_ledger_delta_nonzero", sql`${t.delta} <> 0`),
  ],
);

/** One row per UTC day. Updated in the same transaction as any spend. */
export const dailySpend = pgTable("daily_spend", {
  day: timestamp("day", { withTimezone: true }).primaryKey(),
  spentMicro: bigint("spent_micro", { mode: "number" }).notNull().default(0),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Fixed-window rate limit. In the database rather than in memory so it survives
 * a dev-server restart and works across instances on Vercel.
 */
export const rateLimits = pgTable(
  "rate_limits",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    windowStart: timestamp("window_start", { withTimezone: true }).notNull(),
    count: integer("count").notNull().default(0),
  },
  (t) => [
    uniqueIndex("rate_limits_pk").on(t.userId, t.windowStart),
    check("rate_limits_count_non_negative", sql`${t.count} >= 0`),
  ],
);

/**
 * Written by hand in db/migrate.sql, not by drizzle-kit, because it is a
 * trigger rather than a table. Kept here so it is discoverable next to the
 * table it protects.
 *
 *   CREATE FUNCTION credit_ledger_immutable() RETURNS trigger AS $$
 *   BEGIN
 *     RAISE EXCEPTION 'credit_ledger is append-only';
 *   END;
 *   $$ LANGUAGE plpgsql;
 *
 *   CREATE TRIGGER credit_ledger_no_update BEFORE UPDATE OR DELETE
 *     ON credit_ledger FOR EACH ROW EXECUTE FUNCTION credit_ledger_immutable();
 */
export const ledgerImmutabilitySql = `
CREATE OR REPLACE FUNCTION credit_ledger_immutable() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'credit_ledger is append-only; % is not permitted', TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS credit_ledger_no_mutation ON credit_ledger;
CREATE TRIGGER credit_ledger_no_mutation
  BEFORE UPDATE OR DELETE ON credit_ledger
  FOR EACH ROW EXECUTE FUNCTION credit_ledger_immutable();
`;

export const usersRelations = relations(users, ({ many }) => ({
  generations: many(generations),
  ledger: many(creditLedger),
}));

export const generationsRelations = relations(generations, ({ one, many }) => ({
  user: one(users, { fields: [generations.userId], references: [users.id] }),
  ledger: many(creditLedger),
}));

export const creditLedgerRelations = relations(creditLedger, ({ one }) => ({
  user: one(users, { fields: [creditLedger.userId], references: [users.id] }),
  generation: one(generations, { fields: [creditLedger.generationId], references: [generations.id] }),
}));

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Generation = typeof generations.$inferSelect;
export type NewGeneration = typeof generations.$inferInsert;
export type CreditLedgerEntry = typeof creditLedger.$inferSelect;
export type GenerationStatus = (typeof generationStatus.enumValues)[number];
export type GenerationType = (typeof generationType.enumValues)[number];
export type LedgerReason = (typeof ledgerReason.enumValues)[number];
